### ISSUE TITLE
Not auto-updating to Packagist

### ISSUE THREAD

**Issue by claybitner** [chocoholics/laravel-elastic-email#11]
Although there is a new version on github, it is not automatically being sent to packagist for composer. 

Packagist says this when looking at the listing for laravel-elastic-email: "(Legacy Auto-Update, Needs Attention)"

See here for resolution: [https://stackoverflow.com/questions/53138396/legacy-auto-update-needs-attention](https://stackoverflow.com/questions/53138396/legacy-auto-update-needs-attention)

Additionally, packigist says to do this: 
> If you have published packages from GitHub on packagist.org please logout/login with GitHub to let us upgrade the auto-update hooks and remove the deprecated GitHub service hooks. See "GitHub Hook" on [packagist.org/about#how-to-u](https://t.co/uJnB19KGaI?amp=1)… for more details.

Taken from here: 
https://github.com/composer/packagist/issues/907

**Comment by driftdares** [comment]
Thanks @claybitner for the heads up. I have made the suggested changes and it appears to be working.
