### ISSUE TITLE
laravel 5.5 

### ISSUE THREAD

**Issue by fahjan** [chocoholics/laravel-elastic-email#2]
Problem 1
    - Installation request for chocoholics/laravel-elastic-email ^0.0.4 -> satisfiable by chocoholics/laravel-elastic-email[v0.0.4].
    - chocoholics/laravel-elastic-email v0.0.4 requires laravel/framework 5.1.x|5.2.x|5.3.x|5.4.x -> satisfiable by laravel/framework[5.1.x-dev, 5.2.41, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.44, v5.1.45, v5.1.46, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21,
v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36,
v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.

**Comment by galdazbiz** [comment]
I'm interested in this too... I hope the dev solve it :)

**Comment by driftdares** [comment]
Thanks for the interest, I'll work on it..

**Comment by galdazbiz** [comment]
thank you so much! I guess is not as easy as changing this right?
 https://github.com/chocoholics/laravel-elastic-email/pull/1/files

Would it be possible to know when you'll have time to solve it? There aren't so many libraries for this elastic email.. and this looks quite good.

**Comment by driftdares** [comment]
Thanks @galdazbiz for the PR. I have merged it and updated the release to v0.0.5

**Comment by galdazbiz** [comment]
thanks for being so quick, have your tried it? For some reason is not getting it correctly

Using version ^0.0.5 for chocoholics/laravel-elastic-email
Problem 1
    - Installation request for ashrey/laravel-elastic-email-rate dev-master -> satisfiable by ashrey/laravel-elastic-email-rate[dev-master].
    - ashrey/laravel-elastic-email-rate dev-master requires laravel/framework 5.1.x|5.2.x|5.3.x|5.4.x

**Comment by driftdares** [comment]
I havent tested it. I was hoping for a quick fix but I may have to work on it later today..

**Comment by tronne** [comment]
I just did the migration to 5.5 and same problem here, it's good you're already working on this.

**Comment by driftdares** [comment]
@galdazbiz and @tronne, please try it with the latest release v0.0.6 and let me know if that works.

**Comment by galdazbiz** [comment]
emm, not lucky :( am I doing something wrong?

Using version ^0.0.6 for chocoholics/laravel-elastic-email
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ashrey/laravel-elastic-email-rate dev-master -> satisfiable by ashrey/laravel-elastic-email-rate[dev-master].
    - ashrey/laravel-elastic-email-rate dev-master requires laravel/framework 5.1.x|5.2.x|5.3.x|5.4.x -> satisfiable by laravel/framework[5.1.x-dev, 5.

**Comment by driftdares** [comment]
@galdazbiz What is ashrey/laravel-elastic-email ? 

Also, I am testing this on my end and realised it's not such an easy fix, because L5.5 now uses SwiftMailer ~v6. I'll need to tweak the mailer to remain compatible. I'm working on it right now

**Comment by galdazbiz** [comment]
I just tried with version 0.0.7 and composer its working!!
BTW ashrey/laravel-elastic-email-rate dev-master was a github copy of your code from someone I think

**Comment by driftdares** [comment]
@galdazbiz Glad to hear it! I haven't used Elastic Email in a while so I had to create a new project to test it. I thought I could get away with just changing the version in composer.json but turns out there were breaking changes in L5.5. I'm glad it's now working--time well spent on a Sunday morning!

**Comment by galdazbiz** [comment]
thank you very much!!! I appreciate it a lot, I'm not very experienced coder and you've saved me a lot of time :) So happy, thanks again!
