### ISSUE TITLE
Laravel Elastic Email failing to install on Laravel v5.6.11

### ISSUE THREAD

**Issue by njoguamos** [chocoholics/laravel-elastic-email#6]
Steps (laravel 5.6.11)
Run: `composer require chocoholics/laravel-elastic-email`

Terminal Results:
=>Using version ^0.0.7 for chocoholics/laravel-elastic-email
=>./composer.json has been updated
=>Loading composer repositories with package information
=>Updating dependencies (including require-dev)

=>Your requirements could not be resolved to an installable set of packages.

=>Problem 1
    - Installation request for chocoholics/laravel-elastic-email ^0.0.7 -> satisfiable by chocoholics/laravel-elastic-email[v0.0.7].
    - Conclusion: remove laravel/framework v5.6.11
    - Conclusion: don't install laravel/framework v5.6.11
    - chocoholics/laravel-elastic-email v0.0.7 requires laravel/framework 5.1.x|5.2.x|5.3.x|5.4.x|5.5.x -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.1.x-dev, v5.6.11].
    - Can only install one of: laravel/framework[5.2.x-dev, v5.6.11].
    - Can only install one of: laravel/framework[5.3.x-dev, v5.6.11].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.6.11].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.11].
    - Installation request for laravel/framework (locked at v5.6.11, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.11].

**Comment by driftdares** [comment]
Please use v0.0.8. Thanks!
